/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
    './views/**/*.php',
    './widgets/**/*.php',
    './helpers/**/*.php',
    './controllers/**/*.php',
    './web/js/**/*.js',
    ],
    theme: {
        extend: {
            colors: {
                acid: {
                    lime: '#4F46E5',   // индиго — primary
                    cyan: '#0EA5E9',   // голубой — secondary
                    violet: '#7C3AED',   // фиолет — accent
                    pink: '#E11D48',   // красный — danger
                },
                base: {
                    950: '#F8FAFC',      // фон страницы
                    900: '#F1F5F9',      // фон карточек
                    800: '#E2E8F0',      // фон панелей / инпутов
                    700: '#CBD5E1',      // бордеры
                    400: '#94A3B8',      // muted text
                    100: '#0F172A',      // основной текст
                },
            },
            backgroundImage: {
                'grad-lime-cyan': 'linear-gradient(135deg, #4F46E5 0%, #0EA5E9 100%)',
                'grad-violet-pink': 'linear-gradient(135deg, #7C3AED 0%, #E11D48 100%)',
                'grad-card': 'linear-gradient(145deg, #FFFFFF 0%, #F8FAFC 100%)',
            },
            boxShadow: {
                'glow-lime': '0 0 24px 0 rgba(79,70,229,0.18)',
                'glow-cyan': '0 0 24px 0 rgba(14,165,233,0.18)',
                'glow-violet': '0 0 24px 0 rgba(124,58,237,0.15)',
                'card': '0 1px 3px 0 rgba(0,0,0,0.07), 0 4px 16px 0 rgba(0,0,0,0.05)',
                'card-hover': '0 4px 6px 0 rgba(0,0,0,0.07), 0 10px 32px 0 rgba(0,0,0,0.10)',
                'input-focus': '0 0 0 3px rgba(79,70,229,0.15)',
            },
            fontFamily: {
                sans: ['Inter', 'system-ui', 'sans-serif'],
                mono: ['JetBrains Mono', 'monospace'],
            },
        },
    },
    plugins: [],
safelist: [
    'callout-example',
    'callout-definition',
    'callout-note',
    'callout-warning',
    'callout-badge',
    'callout-title',
    'callout-body',
    'page-toc',
    'page-toc-title',
    'is-h3',
    'is-active',
    'book-nav-page-sub',
    'task-accent-1',
    'task-accent-2',
    'task-accent-3',
    'task-accent-4',
    'is-active-scroll',
    'py-run-wrapper',
    'py-run-toolbar',
    'py-run-btn',
    'py-run-output',
    'py-status-banner',
    'py-status-dot',
    'py-status-text',
    'is-hidden',
    'is-ready',
    'is-error',
    'py-run-output-tall',
    'py-modal',
    'py-modal-backdrop',
    'py-modal-panel',
    'py-modal-header',
    'py-modal-title',
    'py-modal-close',
    'py-modal-body',
    'py-modal-editor-col',
    'py-modal-output-col',
    'py-modal-output-label',
    'py-modal-output',
    'py-modal-footer',
    'py-code-holder',
    'py-float-run-btn',
    'py-run-output-tall',
    'ns-step',
    'ns-step-title',
    'ns-expansion',
    'ns-term',
    'ns-sup',
    'ns-plus',
    'ns-expansion-values',
    'ns-expansion-result',
    'ns-div-table',
    'ns-div-row',
    'ns-div-num',
    'ns-div-op',
    'ns-div-rem',
    'ns-div-readout',
    'ns-readout-digits',
    'ns-general-formula',
    'ns-digit-table',
    'ns-digit-col',
    'ns-digit-value',
    'ns-digit-power',
    'ns-same-base-warning',
    'tool-layout',
    'tool-main',
    'tool-sidebar',
    'tt-op-btn',
    'tt-table',
    'tt-th-result',
    'tt-td-result',
    'ns-katex-block',
    'ns-theory-list',
    'ns-theory-row',
    'fano-row',
    'fano-decode-steps',
    'fano-decode-step',
    'fano-decode-code',
    'fano-decode-arrow',
    'fano-decode-symbol',
    'home-layout',
    'home-main',
    'home-sidebar',
    'graph-mode-btn',
    'is-active',
    'graph-canvas-card',
    'graph-panels-row',
    'graph-panel-col',
    'graph-list',
    'graph-list-row',
    'graph-opts',
    'graph-svg-textarea',
    'graph-matrix',
    'graph-matrix-on',
    'graph-dist-row',
    'task-pill',
    'task-pill-active',
    'task-pill-wide',
    'task-tag-pill',
    'task-tag-pill-active',
    'py-icon-btn',
    'py-icon-btn-primary',
    'is-loading',
    'py-input-row',
    'py-input-field',
    'py-icon-btn-warming',
    'py-icon-btn-warming',
    'py-modal-close',
    'difficulty-pill',
    'difficulty-pill-easy',
    'difficulty-pill-medium',
    'difficulty-pill-hard',
    ],
}