<?php
return [
    // --- Auth ---
    'login'                => 'auth/login',
    'logout'               => 'auth/logout',
    'register/<token>'     => 'auth/register',
    'password-reset'       => 'auth/password-reset',
    'password-reset/<token>' => 'auth/password-reset-confirm',

    // --- Публичная часть ---
    'book'                        => 'book/index',
    'book/<sectionSlug:[\w-]+>'   => 'book/section',
    'book/<sectionSlug:[\w-]+>/<chapterSlug:[\w-]+>/<slug:[\w-]+>' => 'book/view',
    'python' => 'python/index',

    'rating'  => 'rating/index',
    'signup'  => 'auth/signup',

    'tools'                 => 'tools/index',
    'tools/number-systems'  => 'tools/number-systems',
    'tools/bits-bytes' => 'tools/bits-bytes',
    'tools/truth-table' => 'tools/truth-table',
    'tools/fano' => 'tools/fano',
    'tools/graph-editor' => 'tools/graph-editor',

    'tasks'                => 'task/index',
    'tasks/<id:\d+>'       => 'task/view',

    'notifications'               => 'notification/index',
    'notifications/mark-all-read' => 'notification/mark-all-read',
    'notifications/clear-all'     => 'notification/clear-all',

    // --- Student ---
    'student/challenge/submit/<id:\d+>' => 'student/challenge/submit',
    'student/course'                                     => 'student/course/index',
    'student/course/view/<courseId:\d+>'                 => 'student/course/view',
    'student/course/choose-duration/<courseId:\d+>'      => 'student/course/choose-duration',
    'student/course/change-duration/<enrollmentId:\d+>'  => 'student/course/change-duration',
    'student/course/mark-read/<lessonId:\d+>' => 'student/course/mark-read',
    'student/exam/view/<id:\d+>'    => 'student/exam/view',
    'student/exam/answer/<id:\d+>'  => 'student/exam/answer',
    'student/exam/submit/<id:\d+>'  => 'student/exam/submit',
    'student/exam/heartbeat/<id:\d+>' => 'student/exam/heartbeat',
    'student/exam/result/<id:\d+>'  => 'student/exam/result',
    'student/homework/upload-file/<id:\d+>' => 'student/homework/upload-file',
    'student/homework/view/<id:\d+>'   => 'student/homework/view',
    'student/homework/result/<id:\d+>' => 'student/homework/result',
    'student/homework/submit/<id:\d+>' => 'student/homework/submit',
    'student/homework/retry/<id:\d+>'  => 'student/homework/retry',
    'student/homework/save-draft/<id:\d+>' => 'student/homework/save-draft',
    'student/timeline/generate-share-link' => 'student/timeline/generate-share-link',
    'student/schedule'                => 'student/schedule/index',
    'student/schedule/view/<id:\d+>' => 'student/schedule/view',
    'student/timeline'                => 'student/timeline/index',
    'student'                                          => 'student/dashboard/index',
    'student/<controller:[\w-]+>'                      => 'student/<controller>/index',
    'student/<controller:[\w-]+>/<action:[\w-]+>'      => 'student/<controller>/<action>',
    'student/<controller:[\w-]+>/<action:[\w-]+>/<id:\d+>' => 'student/<controller>/<action>',

    // --- Teacher ---
    'teacher/exam/view/<id:\d+>'    => 'teacher/exam/view',
    'teacher/exam/attempt/<id:\d+>' => 'teacher/exam/attempt',
    'teacher/exam/update/<id:\d+>'  => 'teacher/exam/update',
    'teacher/exam/delete/<id:\d+>'  => 'teacher/exam/delete',
    'teacher/exam/archive/<id:\d+>' => 'teacher/exam/archive',

    'teacher/homework/group-task-ids' => 'teacher/homework/group-task-ids',
    'teacher/homework/submissions/<id:\d+>' => 'teacher/homework/submissions',
    'teacher/homework/review/<id:\d+>'      => 'teacher/homework/review',
    'teacher/group/view/<id:\d+>'           => 'teacher/group/view',
    'teacher/group/add-student/<id:\d+>'    => 'teacher/group/add-student',
    'teacher/group/remove-student/<id:\d+>' => 'teacher/group/remove-student',
    'teacher/group/timeline/<id:\d+>' => 'teacher/group/timeline',
    'teacher/homework/view/<id:\d+>'        => 'teacher/homework/view',
    'teacher/lesson/view/<id:\d+>'  => 'teacher/lesson/view',
    'teacher/slide/present/<id:\d+>' => 'teacher/slide/present',
    'teacher'                                          => 'teacher/dashboard/index',
    'teacher/<controller:[\w-]+>'                      => 'teacher/<controller>/index',
    'teacher/<controller:[\w-]+>/<action:[\w-]+>'      => 'teacher/<controller>/<action>',
    'teacher/<controller:[\w-]+>/<action:[\w-]+>/<id:\d+>' => 'teacher/<controller>/<action>',
    'teacher/schedule/view/<id:\d+>'     => 'teacher/schedule/view',
    'teacher/schedule/complete/<id:\d+>' => 'teacher/schedule/complete',
    'teacher/schedule/cancel/<id:\d+>'   => 'teacher/schedule/cancel',
    'teacher/schedule/update/<id:\d+>'     => 'teacher/schedule/update',
    'teacher/schedule/reschedule/<id:\d+>' => 'teacher/schedule/reschedule',



    // --- Admin ---
    'admin/rating/weights'          => 'admin/rating/weights',
    'admin/rating/challenges'       => 'admin/rating/challenges',
    'admin/rating/create-challenge' => 'admin/rating/create-challenge',
    'admin/course/view/<id:\d+>'            => 'admin/course/view',
    'admin/course/create-lesson'            => 'admin/course/create-lesson',
    'admin/course/update-lesson/<id:\d+>'   => 'admin/course/update-lesson',
    'admin/course/delete-lesson/<id:\d+>'   => 'admin/course/delete-lesson',
    'admin/course/move-lesson/<id:\d+>/<direction:up|down>' => 'admin/course/move-lesson',
    'admin/course/process-unlocks' => 'admin/course/process-unlocks',
    'admin/landing/preview' => 'admin/landing/preview',
    'admin/exam/delete/<id:\d+>' => 'admin/exam/delete',
    'admin/exam/assign-checkpoint' => 'admin/exam/assign-checkpoint',
    'admin/exam/all'               => 'admin/exam/all',
    'admin/lead/toggle-processed/<id:\d+>' => 'admin/lead/toggle-processed',
    'admin/content/book-sections'          => 'admin/content/book-sections',
    'admin/content/create-section'         => 'admin/content/create-section',
    'admin/content/update-section/<id:\d+>' => 'admin/content/update-section',
    'admin/content/delete-section/<id:\d+>' => 'admin/content/delete-section',
    'admin/content/book'                          => 'admin/content/book',
    'admin/content/create-chapter'                => 'admin/content/create-chapter',
    'admin/content/update-chapter/<id:\d+>'       => 'admin/content/update-chapter',
    'admin/content/delete-chapter/<id:\d+>'       => 'admin/content/delete-chapter',
    'admin/content/create-page'                   => 'admin/content/create-page',
    'admin/content/update-page/<id:\d+>'          => 'admin/content/update-page',
    'admin/content/delete-page/<id:\d+>'          => 'admin/content/delete-page',
    'admin/content/toggle-page-status/<id:\d+>'   => 'admin/content/toggle-page-status',
    'admin/content/render-preview'                => 'admin/content/render-preview',
    'admin/content/reorder-pages' => 'admin/content/reorder-pages',
    'admin/content/toggle-section-status/<id:\d+>' => 'admin/content/toggle-section-status',
    'admin/content/toggle-chapter-status/<id:\d+>' => 'admin/content/toggle-chapter-status',
    'admin/user/view/<id:\d+>'            => 'admin/user/view',
    'admin/user/assign-teacher/<id:\d+>'  => 'admin/user/assign-teacher',
    'admin/media/picker' => 'admin/media/picker',
    'admin/media/upload' => 'admin/media/upload',
    'admin/lesson/view/<id:\d+>'                        => 'admin/lesson/view',
    'admin/lesson/move-topic/<id:\d+>/<direction:up|down>'  => 'admin/lesson/move-topic',
    'admin/lesson/move-lesson/<id:\d+>/<direction:up|down>' => 'admin/lesson/move-lesson',
    'admin/lesson/delete/<id:\d+>' => 'admin/lesson/delete',
    'admin/slide/edit/<id:\d+>'         => 'admin/slide/edit',
    'admin/slide/add-slide/<id:\d+>'    => 'admin/slide/add-slide',
    'admin/slide/update-slide/<id:\d+>' => 'admin/slide/update-slide',
    'admin/slide/delete-slide/<id:\d+>' => 'admin/slide/delete-slide',
    'admin/slide/move-slide/<id:\d+>/<direction:up|down>' => 'admin/slide/move-slide',
    'admin/slide/delete-deck/<id:\d+>'  => 'admin/slide/delete-deck',
    'admin/<controller:[\w-]+>/tag-update/<id:\d+>' => 'admin/<controller>/tag-update',
    'admin/<controller:[\w-]+>/tag-delete/<id:\d+>' => 'admin/<controller>/tag-delete',
    'admin/<controller:[\w-]+>/toggle-status/<id:\d+>' => 'admin/<controller>/toggle-status',
    'admin/<controller:[\w-]+>/delete/<id:\d+>'        => 'admin/<controller>/delete',
    'admin'                                            => 'admin/dashboard/index',
    'admin/settings' => 'admin/settings/index',
    'admin/<controller:[\w-]+>'                        => 'admin/<controller>/index',
    'admin/<controller:[\w-]+>/<action:[\w-]+>'        => 'admin/<controller>/<action>',
    'admin/<controller:[\w-]+>/<action:[\w-]+>/<id:\d+>' => 'admin/<controller>/<action>',
    'admin/<controller:[\w-]+>/delete-file/<id:\d+>' => 'admin/<controller>/delete-file',
    // --- Файлы (отдача через контроллер) ---
    'files/<path:.+>'      => 'file/get',

    'parent/timeline/<token>'         => 'parent/timeline/view',

    // --- Лендинги — последнее правило ---
    '<slug:[\w-]+>'        => 'landing/view',

    'notifications/count' => 'notification/count',
    'notifications/panel' => 'notification/panel',
    // Лендинги — заявка (форма отправляет POST на публичный роут)
    'lead/create/<landingId:\d+>' => 'landing/create-lead',

    // Sitemap и robots
    'sitemap.xml' => 'site/sitemap',
    'robots.txt'  => 'site/robots',
];
